language: node_js
node_js:
- '8'
script:
- npm run test --ci --coverage
- npm run build
deploy:
  provider: npm
  email: kou64yama@gmail.com
  api_key:
    secure: Nffe1kKAPebc9TFXXHehd9oXgzaymMaL5FqWwFLsJRIRNRPTVpT1/hiyUPIe1edIC8k9fQPcJaoIJxsMdxrLYyrtM8Zl1nn3wr/hIXkJF3CgfLSQg3gHrlwttBqdZIfxm5T1j+bBxzpBjIdIc8SqAMF0ZLnnQzyqeNWD4hNB+BaxkVBPA4ebWy97YebgZdyLrbpFkQmBAO8mQa85aXEsm4ARdHQR3F0EJBWxVcsQhCn6YbgUOboj/9ukbdt++2wtXwfxdSmNYxylHdvyv0Uyp8INGaM723GBcA3kpl6Cw+zijNoEGSeNuNNpV8cIAhEHCT+fHMgA+03+5i97CKtVlvPv+yYcmFKrZHWdYHkkQVetf09VA6Vz/7gFi/Jgs01k7Ns0S3ujv7G69GfhxMi62tT0XMr59LIsW56xyKfI2Frhh5D58M8Q223ji6eyGfbkPg4NWKscmTEUrNgiSL4Nn846NQyPB55ilOpDr+FOgmP1SqGFVKqMK7vQGy5wLMOAWp826okjv0djQAncY2i72GvPsNRNSMX0+hTocofyGmcIE4eMIrs3ZlFs8aULCderW4tM6BA4xha50MLwsnl+1ODBnopZ29tjgGcC4s2aNU6T+LSk6o4S0MmmI6n6o1MmnVR0xm1L4JjsYG4jijzhJn3k4SxJ84zSlAXQWKfb9So=
  on:
    tags: true
    repo: kou64yama/nobushi-config
