language: node_js
node_js:
- '7'
script:
- npm run test
deploy:
  provider: npm
  email: kou64yama@gmail.com
  api_key:
    secure: mJqhUSbiwq+Wflb4osH8pxg92KUEdrFxpovosRWg28rCGnCTCJd2G8nkeRuQv7QxqUTmW032qvXD2Zzu8y1JeNe0RDGzy7h85xfWs1KQxOPdftQ39SY6fNJorZu9plRQA3fhX+WRkxXhAlytq8oMtB6nFKZ0Q6ASz1aHvDfmaSTo27kSQLmE5MQ3Euxnj5VtJbHnb1ampm/upF288XwDwktP6u0VfWZZ2yiRZ3ypPHJgBZV8T6j2NzpQojqfZNVI5O9XLF5afIL5yLH5FlKgr55sfWN9zrdRQQAe91x2CdQ+5YX/IhQWygjM56wSxZrzPCwd9WWvOIpK7Y7sWOuoohHjXdJM61T/ofjheLXGElDAUMQQzI3ifG7FZyknGU1FaFfO1PbG4CBNWe1tZ+09P4sP+5NYZC6DEyHm6D90l8mQpXG3zt+tv3LYCU5LIAHdibLW0Ug6OkIY7/D3jDIranHW/8gDVu457BzwPDDHZuq29A0eXzgirGMqNKJEpP1+vLQ68Uj28NVRpU3MfRUq6pmq5805E92903SH4fEtELo82P/3c69shLjSOChVFPzHXNw8zNxf026hvRtw33OGwp/L8W1YQpQgWq7As/I+Wne03jE55gRSnqQ93zlKjJzYfrrzOjyOoFxg2hyZj41eUmap3IWwvTZ3gFF59iTFXQ8=
  on:
    tags: true
    repo: kou64yama/nobushi-config
